"""Persist profile event schema and snapshot lineage.

Revision ID: 0007_profile_provenance
Revises: 0006_profile_correction
Create Date: 2026-09-25
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0007_profile_provenance"
down_revision = "0006_profile_correction"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # All pre-migration events were validated against the original v1 whitelist.
    op.add_column(
        "profile_events",
        sa.Column("schema_version", sa.Integer(), nullable=False, server_default="1"),
    )
    op.create_check_constraint(
        "ck_profile_events_schema_version_positive", "profile_events", "schema_version >= 1"
    )

    # Historical snapshots predate persisted rule provenance. Do not claim they
    # were generated by the current rule, even when their content looks similar.
    op.add_column(
        "student_profiles",
        sa.Column(
            "merge_rule_version",
            sa.String(40),
            nullable=False,
            server_default="legacy-profile-v1",
        ),
    )
    op.alter_column("student_profiles", "merge_rule_version", server_default=None)
    op.add_column(
        "student_profiles",
        sa.Column("previous_profile_id", postgresql.UUID(as_uuid=True)),
    )
    op.execute(
        """
        UPDATE student_profiles AS current_profile
        SET previous_profile_id = (
            SELECT prior.id
            FROM student_profiles AS prior
            WHERE prior.user_id = current_profile.user_id
              AND prior.version < current_profile.version
            ORDER BY prior.version DESC
            LIMIT 1
        )
        WHERE current_profile.version > 1
        """
    )
    op.create_foreign_key(
        "fk_student_profiles_previous_profile_id",
        "student_profiles",
        "student_profiles",
        ["previous_profile_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_student_profiles_previous_profile_id", "student_profiles", type_="foreignkey"
    )
    op.drop_column("student_profiles", "previous_profile_id")
    op.drop_column("student_profiles", "merge_rule_version")
    op.drop_constraint(
        "ck_profile_events_schema_version_positive", "profile_events", type_="check"
    )
    op.drop_column("profile_events", "schema_version")
